parameters:
    db_prefix: gibbon
    locale: en_GB
    security.hierarchy.roles:
        ROLE_USER: null,
        ROLE_ALLOWED_TO_SWITCH: null
        ROLE_PARENT: [ROLE_USER]
        ROLE_STUDENT: [ROLE_USER]
        ROLE_STAFF: [ROLE_USER]
        ROLE_TEACHER: [ROLE_ALLOWED_TO_SWITCH, ROLE_STUDENT, ROLE_STAFF]
        ROLE_HEAD_TEACHER: [ROLE_TEACHER]
        ROLE_PRINCIPAL: [ROLE_HEAD_TEACHER]
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH]
        ROLE_REGISTRAR: [ROLE_PRINCIPAL, ROLE_ADMIN]
        ROLE_SYSTEM_ADMIN: [ROLE_REGISTRAR, ROLE_PARENT]
    gibbon_document_root: 'f:\websites\crayner\Gibbon\'