security:
    encoders:
        App\Entity\Person:
            algorithm: sha256
    providers:
        security_user_provider:
            entity:
                class:  App\Entity\Person
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|home)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path:           login
                check_path:           login
                csrf_parameter:       'login[_token]'
                csrf_token_id:        authenticate
                csrf_token_generator: security.csrf.token_manager
                username_parameter:   'login[_username]'
                password_parameter:   'login[_password]'
                success_handler:      App\Security\LoginSuccessHandler
            provider:                 security_user_provider
            logout:
                path:                 logout
                target:               home
                success_handler:      App\Security\LogoutSuccessHandler
            remember_me:              false
            #                secret:               '%env(APP_SECRET)%'
            #                name:                 '%session_name%_remember_me'
            #                lifetime:             43200 # 12 hours in seconds
            #                path:                 /
            #                secure:               false
            #                remember_me_parameter: 'login[_remember_me]'
            switch_user:              true
            guard:
                authenticators:
                    - App\Manager\GoogleAuthenticator
    role_hierarchy: '%security.hierarchy.roles%'