language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - phy: 7.1
    - phy: 7.2

# optionally specify a list of environments, for example to test different RDBMS
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit
env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

before_install:
  - cp .env.local.test .env.local
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  # Disable x-debug to speed up things
  - phpenv config-rm xdebug.ini
  # add composer global bin to PATH to make codeception usable
  - export PATH=$HOME/.composer/vendor/bin:$PATH

script:
  - ./vendor/bin/phpunit