language: php

# The platforms you wants to test on
dist: trusty
os:
  - linux

php:
  - 7.2
  - 7.3

# faster builds on new travis setup not using sudo
sudo: false

# set git depth to reduce download size
git:
  depth: 2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache


# optionally specify a list of environments, for example to test different RDBMS
env:
  global:
    - CI_PLATFORM='travis_ci'
    - ABSOLUTE_URL='http://127.0.0.1:8888'

install:
  - cp .env.local.test .env.local
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction
  - travis_retry composer update --no-interaction

before_install:
  # Disable x-debug to speed up things
  - phpenv config-rm xdebug.ini
  # add composer global bin to PATH to make codeception usable
  - export PATH=$HOME/.composer/vendor/bin:$PATH

#script:
#  - $HOME/symfony-bridge/.phpunit

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - php -S 127.0.0.1:8888 -t $TRAVIS_BUILD_DIR >/dev/null 2>&1 &
  - sleep 1
  - ./vendor/bin/simple-phpunit --version

script:
  - ./vendor/bin/simple-phpunit --configuration ./phpunit.xml.dist ./tests/

