language: php

php:
  - 7.1
  - 7.2
  - 7.0
  - nightly

matrix:
  fast_finish: true
# optionally specify a list of environments, for example to test different RDBMS
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit
env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

before_script:
  - cp .env.local.test .env.local
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

before_install:
  # Disable x-debug to speed up things
  - phpenv config-rm xdebug.ini
  # add composer global bin to PATH to make codeception usable
  - export PATH=$HOME/.composer/vendor/bin:$PATH

script:
  - $HOME/symfony-bridge/.phpunit