_home:
    path: /
    controller: App\Controller\LocaleController::home
google_oauth:
    path: "/connect/google/"
    controller: App\Controller\OAuthController::connectGoogle
connect_google_check:
    path: "/security/oauth2callback/"
    controller: App\Controller\OAuthController::connectCheckGoogle
logout:
    path: '/logout/'
    controller: App\Controller\SecurityController::logout
