controllers:
    resource: ../../src/Controller/
    prefix:   /{_locale}
    requirements:
        _locale: '%locale%'
    defaults:
        _locale: en
    type: annotation
_home:
    path: /
    controller: App\Special\Controller\LocaleController::home
